### ISSUE TITLE
Luxafor Mute

### ISSUE THREAD

**Issue by jamesmdavies88** [jamesrwilliams/luxafor-py#1]
Hi James,

Came across your repo when trying to put a script together in Python for my Luxafor Mute to work with Linux.

Took me a while to figure out how the data should be sent to the device to control the colours, and hope that what I have done can help you with your project (as there doesn't seem to be many projects out there for Mute, seems to only be projects for other Luxafor products).

https://github.com/jamesmdavies88/LuxaforMute

Thanks,

James.

**Comment by jamesrwilliams** [comment]
Hey @jamesmdavies88 👋  

Thanks for the comment, and the additional context from project will be very useful!

All the best,

James W.
